import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#2d3436",
        "tertiary-container": "#cba72f",
        "on-primary-fixed": "#161d1f",
        "on-primary-container": "#959c9f",
        "outline": "#747879",
        "on-primary": "#ffffff",
        "surface-bright": "#f9f9f9",
        "outline-variant": "#c3c7c8",
        "on-surface-variant": "#434749",
        "surface": "#f9f9f9",
        "secondary-fixed-dim": "#adcdc3",
        "tertiary-fixed-dim": "#e9c349",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#241a00",
        "primary-fixed-dim": "#c1c8ca",
        "primary-fixed": "#dde4e6",
        "error": "#ba1a1a",
        "secondary": "#46645c",
        "on-primary-fixed-variant": "#41484a",
        "error-container": "#ffdad6",
        "tertiary": "#735c00",
        "on-error-container": "#93000a",
        "surface-container": "#eeeeee",
        "on-tertiary-fixed-variant": "#574500",
        "on-tertiary-container": "#4e3d00",
        "inverse-primary": "#c1c8ca",
        "on-secondary-fixed": "#01201a",
        "background": "#f9f9f9",
        "surface-variant": "#e2e2e2",
        "on-secondary-container": "#4c6a62",
        "inverse-surface": "#2f3131",
        "on-secondary-fixed-variant": "#2f4c45",
        "surface-container-highest": "#e2e2e2",
        "primary": "#181f21",
        "surface-container-low": "#f3f3f3",
        "on-error": "#ffffff",
        "secondary-fixed": "#c8eadf",
        "on-tertiary": "#ffffff",
        "surface-tint": "#586062",
        "secondary-container": "#c8eadf",
        "surface-container-high": "#e8e8e8",
        "on-surface": "#1a1c1c",
        "tertiary-fixed": "#ffe088",
        "inverse-on-surface": "#f1f1f1",
        "on-background": "#1a1c1c",
        "surface-dim": "#dadada",
        "surface-container-lowest": "#ffffff"
      },
      fontFamily: {
        "headline": ["var(--font-manrope)", "sans-serif"],
        "body": ["var(--font-inter)", "sans-serif"],
        "label": ["var(--font-inter)", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
export default config;
